name: Build And Deploy Joraph
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false
      CODECOV_TOKEN: fcaaf858-f58f-46b4-bdf6-08bcdb6d485d
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon --max-workers=2 --warning-mode=all build -x test

      - name: Test
        run: ./gradlew --no-daemon --max-workers=2 --warning-mode=all test --continue

      - name: Upload Coverage Report
        run:  bash <(curl -s https://codecov.io/bash)
